### ISSUE TITLE
Is that possible to add an export function ?

### ISSUE THREAD

**Issue by ghost613** [gentlespoon/USCIS-Case-BatchQuery#2]
Hi, gentlespoon,

I am applying the EAD as well and find your tool very useful.  However, due to the rate limit, I cannot query too many cases in one day.  So I am planning to parse the data little by little and get the idea what the processing I would expect.   Is that possible to save the output into a csv file and I can do analysis using other software ?  Thanks

**Comment by gentlespoon** [comment]
Thanks for the suggestion. I will add it in the next version.
For now, you may select (by dragging), copy and paste the fetched data for analysis.
