### ISSUE TITLE
Not working with cases starting with 0 as the first of the 10 numbers

### ISSUE THREAD

**Issue by marolio** [gentlespoon/USCIS-Case-BatchQuery#9]
Hi!

I noticed that its not working with cases when the first number is 0.
All the IOE cases start with 0, and therefore its not working with IOE cases.

For instance, if I enter IOE0906929443 as the base case, it will scrap the case without the first 0, in this case, it will scrape the case IOE906929443 (the 0 after the E is missing) and show invalid receipt number.

Is there any possibility to modify that?
Im running the latest available .DMG package on Mac OS X Catalina

Thanks a LOT in advance!

![image](https://user-images.githubusercontent.com/58900558/70859315-42cdf680-1ef0-11ea-80f1-5526ab513951.png)

**Comment by marolio** [comment]
Just in case anyone is having this problem, I have """"fixed"""" it by changing this parameters:

./src/app/app.component.ts:    var prefix = this.configService.config.baseCaseID.substring(0, **4**).toUpperCase();
./src/app/app.component.ts:    var caseId = parseInt(this.configService.config.baseCaseID.substring(**4**, 13));

Of course its not proper coding but im by no means a programmer

**Comment by gentlespoon** [comment]
It should be fixed in the latest commit.
Will create a new release when I get access to my Mac at home.

**Comment by marolio** [comment]
Thank you GentleSpoon!.

I'll create another "Issue" with this, but would it be possible to import a txt file or something with predefined case numbers? Because im focused only in a certain type of case and I have the list of only those cases. This way I would be able to check a list of around 25000 cases without scrapping the around 700000 cases in between and being blacklisted from the website


thanks a lot in advance!

**Comment by gentlespoon** [comment]
Sure. Should be easy. Will do it this week.

**Comment by gentlespoon** [comment]
The list importing feature has been implemented.

I have published for Windows, but unfortunately I don't have access to a working to build a DMG at the moment... You may have to build it yourself...
